from __future__ import annotations

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]


README = """# Reliability-Aware ETF Tail-Risk Monitoring

This repository contains the code and experimental materials for **Reliability-Aware ETF Tail-Risk Monitoring**, accepted at IEEE SMC 2026.

The implementation evaluates next-day lower-tail risk for a six-ETF panel using a rolling walk-forward design. The monitoring pipeline combines input-quality diagnostics, quantile prediction, uncertainty scoring, conservative fallback logic, and service alerts. Additional experiments evaluate performance under simulated service-time input degradation and compare the proposed output with standard VaR benchmarks.

## Repository contents

- `run_tail_risk_monitoring.py`: main walk-forward monitoring experiment, component ablations, and quality-validation experiment.
- `compare_gjr_garch.py`: comparison with a GJR-GARCH(1,1)-t VaR benchmark.
- `quality-layer.py`: focused quality-layer validation under prediction-time input corruption.
- `plot.py`: figure-generation utilities.
- `Result/`: representative tables and figures generated by the experiments.

## Data files

Place the following files in the repository root or in the directory specified by `ETF_TAIL_RISK_DATA_DIR`:

- `multiasset_daily_10y_panel_model.csv`
- `VIXCLS.csv`
- `zero_coupon_yield.csv`

Optional input:

- `VXVCLS.csv`

The ETF panel must contain the market fields and precomputed features used by the scripts, including `date`, `symbol`, OHLC prices, volume, returns, rolling volatility measures, range-based volatility proxies, and drawdown variables.

## Environment setup

Python 3.10 or later is recommended.

### Linux and macOS

```bash
python -m venv .venv
source .venv/bin/activate
python -m pip install --upgrade pip
pip install -r requirements.txt
```

### Windows PowerShell

```powershell
python -m venv .venv
.venv\\Scripts\\Activate.ps1
python -m pip install --upgrade pip
pip install -r requirements.txt
```

## Configuration

By default, each script reads data from its own directory. To use another location, set the environment variable before execution.

Linux and macOS:

```bash
export ETF_TAIL_RISK_DATA_DIR=/path/to/data
```

Windows PowerShell:

```powershell
$env:ETF_TAIL_RISK_DATA_DIR = "C:\\path\\to\\data"
```

Experiment parameters are defined in the `Config` dataclass near the top of each analysis script. The principal settings include:

- 5% lower-tail target
- 756-trading-day training window
- 63-trading-day calibration window
- 63-trading-day retraining interval
- five bootstrap quantile models
- 252-day and 63-day historical VaR windows
- uncertainty and quality adjustment coefficients
- 15% prediction-time corruption rate for degradation experiments

## Running the experiments

Main monitoring experiment:

```bash
python run_tail_risk_monitoring.py
```

GJR-GARCH benchmark comparison:

```bash
python compare_gjr_garch.py
```

Focused quality-layer experiment:

```bash
python quality-layer.py
```

The scripts create their output directories automatically. The default directories are:

- `results/`
- `results_gjr_garch/`
- `results_quality_validation/`

## Generating figures

`plot.py` expects `daily_service_outputs.csv` and `monthly_service_summary.csv` in the configured data directory.

```bash
python plot.py
```

Figures are written to the `figures/` subdirectory.

## Reproducibility notes

- Training, calibration, and prediction periods are separated chronologically.
- Calibration offsets use only observations preceding each prediction date.
- Uncertainty states use prior symbol-level uncertainty scores only.
- Synthetic faults are injected only into prediction-time observable inputs.
- Corruption experiments use a fixed seed and fixed design parameters.
- Hyperparameters are specified explicitly in the source files.

## Output interpretation

The reported safe VaR is a lower-tail return threshold. More negative values are more conservative. A breach occurs when the realized next-day return is below the reported threshold. The alert state is an operational diagnostic and is separate from the low/elevated uncertainty split used in the empirical analysis.
"""


REQUIREMENTS = """numpy>=1.24
pandas>=2.0
scipy>=1.10
scikit-learn>=1.3
matplotlib>=3.7
tqdm>=4.66
openpyxl>=3.1
"""


MODULE_HEADERS = {
    "run_tail_risk_monitoring.py": '''"""Reliability-aware ETF tail-risk monitoring experiments.

The module implements the rolling walk-forward monitoring service, uncertainty
and quality diagnostics, conservative fallback rules, component ablations, and
prediction-time input-degradation experiments described in the paper.
"""''',
    "compare_gjr_garch.py": '''"""ETF tail-risk monitoring with a GJR-GARCH benchmark comparison.

The module reproduces the main monitoring experiment and evaluates a
GJR-GARCH(1,1)-t VaR benchmark under the same prediction schedule.
"""''',
    "quality-layer.py": '''"""Quality-layer validation for ETF tail-risk monitoring.

The module evaluates the monitoring service under prediction-time missingness,
stale-price records, and invalid OHLC relationships.
"""''',
}


OUTPUT_NAMES = {
    "run_tail_risk_monitoring.py": "results",
    "compare_gjr_garch.py": "results_gjr_garch",
    "quality-layer.py": "results_quality_validation",
}


BASE_DIR_PATTERN = re.compile(
    r'^\s*BASE_DIR\s*=\s*Path\(os\.environ\.get\('
    r'"ETF_TAIL_RISK_DATA_DIR",\s*Path\(__file__\)\.resolve\(\)\.parent\)\)\s*$',
    re.MULTILINE,
)


def update_analysis_script(filename: str) -> None:
    path = ROOT / filename
    text = path.read_text(encoding="utf-8")
    text = re.sub(r'\A\s*""".*?"""', MODULE_HEADERS[filename], text, count=1, flags=re.DOTALL)
    text, count = BASE_DIR_PATTERN.subn(
        '    base_dir: Path = Path(\n'
        '        os.environ.get(\n'
        '            "ETF_TAIL_RISK_DATA_DIR",\n'
        '            Path(__file__).resolve().parent,\n'
        '        )\n'
        '    )',
        text,
        count=1,
    )
    if count != 1:
        raise RuntimeError(f"Config.base_dir replacement failed in {filename}")

    text, count = re.subn(
        r'^(\s*output_dir_name:\s*str\s*=\s*)"[^"]*"',
        rf'\1"{OUTPUT_NAMES[filename]}"',
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise RuntimeError(f"Output directory replacement failed in {filename}")

    replacements = {
        "# Paper-facing uncertainty diagnostics": "# Uncertainty diagnostics",
        "# Paper-facing rolling low/elevated diagnostic state.": "# Rolling low/elevated diagnostic state.",
        "# Main service backtest (paper default)": "# Main service backtest",
        "# Added: quality validation experiment": "# Quality validation experiment",
        "Legacy fixed-threshold uncertainty buckets kept only for alert logic.": "Fixed-threshold uncertainty buckets used for alert logic.",
        "Paper-facing diagnostic uncertainty state:": "Diagnostic uncertainty state:",
        "paper-facing": "reported",
        "Paper-facing": "Reported",
        "**NEW**: ": "",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    path.write_text(text, encoding="utf-8")


def update_plot_script() -> None:
    path = ROOT / "plot.py"
    text = path.read_text(encoding="utf-8")

    if "import os\n" not in text:
        text = text.replace("from pathlib import Path\n", "from pathlib import Path\nimport os\n", 1)

    occurrences = [m.start() for m in re.finditer(r'^def plot_stress_comparison\(', text, re.MULTILINE)]
    if len(occurrences) > 1:
        second = occurrences[1]
        following = text.find("\ndef plot_monthly_alerts", second)
        if following == -1:
            raise RuntimeError("Duplicate plot function could not be removed")
        text = text[:second] + text[following + 1:]

    replacements = {
        "# 单栏友好；若双栏可改成 (10.5, 3.8)": "# Compact figure size for manuscript use.",
        "# 时间轴：每季度一个刻度，避免太密": "# Use sparse month ticks.",
        "# 更紧的 y 轴，提高可读性": "# Use a compact y-axis range.",
        "# 只保留 y 方向网格": "# Display horizontal grid lines only.",
        "# 图例不要横向铺满一行": "# Use a compact two-column legend.",
        "# 给顶部留足空间，避免数字撞边框/图例": "# Leave space above the bars for labels.",
        "# 图例放右上角图内，避免和数字重叠": "# Place the legend inside the plotting area.",
        "# 柱顶数值标签": "# Add value labels above the bars.",
        "# 不要在图里再加 Figure 3 标题，标题交给 LaTeX caption": "# Figure titles are supplied by the manuscript caption.",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    path.write_text(text, encoding="utf-8")


def validate_repository() -> None:
    prohibited = re.compile(
        r'chatgpt|openai|copilot|claude|gemini|as an ai|ai[- ]generated|generated by ai|'
        r'/Users/|C:\\\\Users\\\\|tenghanz@|keyuanwu@|paper-ready|what is added relative|'
        r'extended version|\*\*NEW\*\*',
        re.IGNORECASE,
    )

    for path in ROOT.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        if path.suffix.lower() not in {".py", ".md", ".txt", ".yml", ".yaml"}:
            continue
        content = path.read_text(encoding="utf-8", errors="ignore")
        match = prohibited.search(content)
        if match:
            raise RuntimeError(f"Prohibited wording remains in {path.relative_to(ROOT)}: {match.group(0)}")

    for filename in MODULE_HEADERS:
        content = (ROOT / filename).read_text(encoding="utf-8")
        if "class Config:" not in content or "base_dir: Path" not in content:
            raise RuntimeError(f"Config validation failed in {filename}")
        if re.search(r'^\s*BASE_DIR\s*=', content, re.MULTILINE):
            raise RuntimeError(f"Obsolete Config.BASE_DIR remains in {filename}")

    plot_text = (ROOT / "plot.py").read_text(encoding="utf-8")
    if plot_text.count("def plot_stress_comparison(") != 1:
        raise RuntimeError("plot.py contains duplicate stress-comparison functions")
    if "import os" not in plot_text:
        raise RuntimeError("plot.py is missing the os import")

    if README.count("```") % 2 != 0:
        raise RuntimeError("README contains an unclosed code block")


def remove_temporary_files() -> None:
    for relative in [
        ".github/repository_cleanup.py",
        ".github/workflows/repository_cleanup.yml",
        ".github/workflows/repository_cleanup_pr.yml",
    ]:
        path = ROOT / relative
        if path.exists():
            path.unlink()


if __name__ == "__main__":
    (ROOT / "README.md").write_text(README, encoding="utf-8")
    (ROOT / "requirements.txt").write_text(REQUIREMENTS, encoding="utf-8")
    for script in MODULE_HEADERS:
        update_analysis_script(script)
    update_plot_script()
    validate_repository()
    remove_temporary_files()
